substitutions:
  # Modify variables based on your settings
  hostname: "d1_mini"
  devicename: d1_mini

esphome:
  name: d1_mini

esp8266:
  #name: esp8266-d1-mini-1
  #platform: ESP8266
  board: d1_mini


## Enable logging
logger:

## Enable Home Assistant API
api:
  encryption:
    key: !secret d1_mini_ota_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  networks:
  - ssid: !secret wifi_ssid_boven
    password: !secret wifi_password_boven
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  ## Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password  
