substitutions:
  # easily modify variables
  hostname: "espcam"
  devicename: espcam

esphome:
  name: "${devicename}"

esp32:
  board: esp32dev

## Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret espcam_ota_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  # manual_ip:
  #   static_ip: !secret static_ip_espcam
  #   gateway: !secret gateway
  #   subnet: !secret subnet
  networks:
  - ssid: !secret wifi_ssid_boven
    password: !secret wifi_password_boven
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  ## Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password


esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]

  # the order of the data_pins is significant, don't mix up the order

  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600
  name: esp_cam02
  idle_framerate: 0.1fps
  max_framerate: 15 fps
  jpeg_quality: 20

output:
  - platform: ledc
    pin: GPIO4
    channel: 2 # channel 1 is used for esp32_camera
    id: led
light:
  - platform: monochromatic
    output: led
    name: espcam_light

### extra device info
sensor:
  - platform: internal_temperature
    name: ${devicename} Internal Temperature

  - platform: wifi_signal
    name: ${devicename} wifi signal
    update_interval: 600s


time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: $devicename Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: $devicename IP
    bssid:
      name: $devicename BSSID


# expose 
esp32_camera_web_server:
  - port: 8080
    mode: STREAM
  - port: 8081
    mode: SNAPSHOT


