substitutions:
  # easily modify variables
  hostname: "espnodemcu2"
  devicename: espnodemcu2

esphome:
  name: espnodemcu2
  friendly_name: espNodeMCU2

esp32:
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret espnodemcu2_ota_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  manual_ip:
    static_ip: !secret static_ip_espnodemcu2
    gateway: !secret gateway
    subnet: !secret subnet
  networks:
  - ssid: !secret wifi_ssid_boven
    password: !secret wifi_password_boven
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  ## Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
### function: 

### temp & humidity
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

sensor:
  - platform: wifi_signal
    name: ${devicename} wifi signal
    update_interval: 600s

time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: $devicename Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: $devicename IP
    bssid:
      name: $devicename BSSID

