substitutions:
  # Modify variables based on your settings
  hostname: "Fan controller"
  devicename: fan_controller

esphome:
  name: fan_controller
  friendly_name: "Fan controller"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

## Enable logging
logger:

## Enable Home Assistant API
api:
  encryption:
    key: !secret fan_controller_ota_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  # manual_ip:
  #   static_ip: !secret static_ip_esp01s
  #   gateway: !secret gateway
  #   subnet: !secret subnet
  networks:
  - ssid: !secret wifi_ssid_boven
    password: !secret wifi_password_boven
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  ## Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
#### my components  above ####
# from 
# https://github.com/patrickcollins12/esphome-fan-controller/blob/master/console-fan.yaml
# START THE FAN CONTROLLER SETUP, but combined with other stuff from:
# https://community.home-assistant.io/t/pwm-fan-controller/433316
# and the ofc claude code

sensor:
  # Every time the fan speed is updated, this sensor will
  # also be updated for displaying on the frontend. 
  # See proxy_output.
  - platform: wifi_signal
    name: ${devicename} wifi signal
    update_interval: 600s

  - platform: pulse_counter
    pin: 
      number: GPIO25   # Connect to any input PIN on the ESP
      mode: INPUT_PULLUP
      ##In file included from src/esphome/components/pulse_counter/pulse_counter_sensor.h:10,
      ##    from src/esphome/components/pulse_counter/pulse_counter_sensor.cpp:1:
      ##  C:/Users/david/.platformio/packages/framework-espidf/components/driver/deprecated/driver/pcnt.h:15:2: warning:
      ##warning "legacy pcnt driver is deprecated, please migrate to use driver/pulse_cnt.h" [-Wcpp]
      ##15 | #warning "legacy pcnt driver is deprecated, please migrate to use driver/pulse_cnt.h"
    unit_of_measurement: 'RPM'
    id: fan_speed
    name: ${devicename} Fan Speed 
    accuracy_decimals: 0
    filters:
      - multiply: 0.5  # Depending
      

output:
  # Wire this pin (13) into the PWM pin of your 12v fan
  # ledc is the name of the pwm output system on an esp32
  - platform: ledc
    id: fan_set_speed
    pin: GPIO13

    # 25KHz is standard PC fan frequency, minimises buzzing
    frequency: "25000 Hz" 

    # my fans stop working below 13% powerful.
    # also they're  powerful and loud, cap their max speed to 80%
    min_power: 0%
    max_power: 80%

    # At 0, actually turn it off, otherwise the power keeps going.
    zero_means_zero: true
  # Read the Tacho PIN and show measured RPM as a sensor (only with 4-pin PWM fans!)
  # See instructions here: https://esphome.io/components/sensor/pulse_counter.html
  
number:
  - platform: template
    name: "Fan Speed Override"
    id: fan_set_speed_value
    internal: false
    max_value: 100.0
    min_value: 0.0
    step: 10
    optimistic: true
    mode: slider
    on_value: 
      then:
        - lambda: |-
            float write_val = x / 100.0;
            id(fan_set_speed).set_level(write_val);


time:
  - platform: homeassistant

#### my components below ####

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: $devicename Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: $devicename IP
    bssid:
      name: $devicename BSSID