[workspace]
channels = ["conda-forge"]
name = "esphome"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]
update = {cmd="python scripts/update_esphome.py"}

[dependencies]
python="3.13.*"

# https://github.com/esphome/esphome
[pypi-dependencies]
esphome="==2026.4.5"
