substitutions:
  # easily modify variables
  hostname: "vindriktning"
  devicename: vindriktning

esphome:
  name: vindriktning
  friendly_name: vindriktning_air_quality

esp32:
  board: wemos_d1_mini32

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret vindriktning_ota_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
    # manual_ip:
    #   static_ip: !secret static_ip_vindriktning
    #   gateway: !secret gateway
    #   subnet: !secret subnet
  networks:
  - ssid: !secret wifi_ssid_boven
    password: !secret wifi_password_boven
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  ## Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password


i2c:
   - id: bus_a
     sda: 21
     scl: 22
     scan: true

uart:
  rx_pin: D3
  baud_rate: 9600


### extra device info
sensor:  
  # #### sensor for temp & humidity
  - platform: bme280_i2c
    i2c_id: bus_a
    address: 0x76
    temperature:
      name: "BME280 Temperature"
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    
  # #### air quality
  - platform: pm1006
    pm_2_5:
      name: "Ikea Vindriktning PM25"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10

  - platform: wifi_signal
    name: ${devicename} wifi signal
    update_interval: 600s
    
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: $devicename Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: $devicename IP
    bssid:
      name: $devicename BSSID
