# https://devices.esphome.io/devices/Sinilink-XY-WFUSB-USB-Switch-Relay
substitutions:
  name: xywfusb
  friendly_name: "XY WF USB Relay"
  default_state: "RESTORE_DEFAULT_OFF"

esphome:
  name: ${name}
  friendly_name: "${friendly_name}"

esp8266:
  board: esp01_1m
  restore_from_flash: True

## Enable logging
logger:

## Enable Home Assistant API
api:
  encryption:
    key: !secret xywfusb_ota_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  fast_connect: True
  power_save_mode: HIGH
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret static_ip_xywfusb
    gateway: !secret gateway
    subnet: !secret subnet
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret wifi_password
    ap_timeout: 3min


time:
  - platform: homeassistant

# Blue LED
status_led:
  pin:
    number: GPIO16

# Relay
switch:
  - platform: gpio
    id: switch_relay
    pin: GPIO5

  # Green LED
  - platform: gpio
    pin: GPIO14
    id: green_led
    inverted: true # start on

  # Switch template to link relay and green LED states
  # LED is on when relay is off
  - platform: template
    id: relay
    name: "${friendly_name}"
    lambda: |-
      if (id(switch_relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
        - switch.turn_on:
            id: green_led
        - switch.turn_on:
            id: switch_relay
    turn_off_action:
        - switch.turn_off:
            id: green_led
        - switch.turn_off:
            id: switch_relay

# Button
binary_sensor:
  - platform: gpio
    id: hardware_button
    pin:
      number: GPIO04
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay